apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: {{ template "radondb-mysql.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  {{- if not .Values.mysql.allowEmptyRootPassword }}
  {{- if .Values.mysql.mysqlRootPassword }}
  mysql-root-password:  {{ .Values.mysql.mysqlRootPassword | b64enc | quote }}
  {{- else }}
  mysql-root-password: {{ randAlphaNum 12 | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- if and .Values.mysql.mysqlUser (and (ne .Values.mysql.mysqlUser "radondb_repl") (ne .Values.mysql.mysqlUser "root")) }}
  {{- if .Values.mysql.mysqlPassword }}
  mysql-password: {{ .Values.mysql.mysqlPassword | b64enc | quote }}
  {{- else }}
  mysql-password: {{ randAlphaNum 12 | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.mysql.mysqlReplicationPassword }}
  mysql-replication-password: {{ .Values.mysql.mysqlReplicationPassword | b64enc | quote }}
  {{- else }}
  mysql-replication-password: {{ randAlphaNum 12 | b64enc | quote }}
  {{- end }}
