apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: {{ template "krypton.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
data:
  node.cnf: |-
{{ .Files.Get "files/node.cnf" | indent 4 }}
  server-id.cnf: |
    [mysqld]
    server-id=@@SERVER_ID@@
  create-peers.sh: |
    #!/bin/bash
    i=0
    while [ $i -lt {{ .Values.replicaCount }} ]
    do
      if [ $i = 0 ]
      then
        echo -n "{{ template "fullname" . }}-${i}.{{ template "fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:8801"
      else
        echo -n ",{{ template "fullname" . }}-${i}.{{ template "fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:8801"
      fi
      let i++
    done
  leader-start.sh: |
    #!/bin/bash
    curl -X PATCH -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" -H "Content-Type: application/json-patch+json" \
    --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_PORT_443_TCP_PORT/api/v1/namespaces/{{ .Release.Namespace }}/pods/$HOSTNAME \
    -d '[{"op": "replace", "path": "/metadata/labels/role", "value": "master"}]'
  leader-stop.sh: |
    #!/bin/bash
    curl -X PATCH -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" -H "Content-Type: application/json-patch+json" \
    --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_PORT_443_TCP_PORT/api/v1/namespaces/{{ .Release.Namespace }}/pods/$HOSTNAME \
    -d '[{"op": "replace", "path": "/metadata/labels/role", "value": "slave"}]'
