# Headless service for stable DNS entries of StatefulSet members.
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: {{ template "krypton.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
    {{- if .Values.service.annotations }}
{{ toYaml .Values.service.annotations | indent 4 }}
    {{- end }}
spec:
  ports:
  - name: {{ template "fullname" . }}
    port: 3306
  clusterIP: None
  selector:
    app: {{ template "fullname" . }}
    release: {{ .Release.Name | quote }}
---
# Client service for connecting to any MySQL instance for writes.
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-master
  labels:
    app: {{ template "fullname" . }}
    chart: {{ template "krypton.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  type: {{ .Values.service.type }}
  {{- if (and (eq .Values.service.type "ClusterIP") (not (empty .Values.service.clusterIP))) }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  {{- if (and (eq .Values.service.type "LoadBalancer") (not (empty .Values.service.loadBalancerIP))) }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
  - name: mysql
    port: {{ .Values.service.port }}
    targetPort: mysql
    {{- if .Values.service.nodePort }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
  selector:
    app: {{ template "fullname" . }}
    release: {{ .Release.Name | quote }}
    role: master
---
# Client service for connecting to any MySQL instance for reads.
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-slave
  labels:
    app: {{ template "fullname" . }}
    chart: {{ template "krypton.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  type: {{ .Values.service.type }}
  {{- if (and (eq .Values.service.type "ClusterIP") (not (empty .Values.service.clusterIP))) }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  {{- if (and (eq .Values.service.type "LoadBalancer") (not (empty .Values.service.loadBalancerIP))) }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
  - name: mysql
    port: {{ .Values.service.port }}
    targetPort: mysql
    {{- if .Values.service.nodePort }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
  selector:
    app: {{ template "fullname" . }}
    release: {{ .Release.Name | quote }}
    role: slave
{{ if .Values.metrics.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "fullname" . }}-metrics"
  labels:
    app: {{ template "fullname" . }}
    chart: {{ template "krypton.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
    {{- if .Values.metrics.annotations }}
{{ toYaml .Values.metrics.annotations | indent 4 }}
    {{- end }}
spec:
  clusterIP: None
  ports:
  - name: metrics
    port: 9104
  selector:
    app: {{ template "fullname" . }}
    release: {{ .Release.Name | quote }}
{{ end }}
