# permissions for end users to view users.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: user-viewer-role
rules:
- apiGroups:
  - mysql.radondb.com
  resources:
  - users
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mysql.radondb.com
  resources:
  - users/status
  verbs:
  - get
