apiVersion: v2
name: xenondb
description: Fast, reliable, scalable, and easy to use open-source relational database system.
home: https://github.com/radondb/xenondb.git

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.0.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "5.7.33"

kubeVersion: ">=1.17.0-0"
sources:
- https://github.com/radondb/xenondb
keywords:
- xenondb
- MySQL HA
- database
- kubernetes

maintainers:
- email: andyli@yunify.com
  name: andy
- email: changlongguan@yunify.com
  name: guanchanglong
- email: zuqianzhang@yunify.com
  name: zhangzuqian
- email: jasongao@yunify.com
  name: jason
- email: runkecheng@yunify.com
  name: rinker
- email: runkecheng@yunify.com
  name: rinker

icon: https://github.com/KID-G/krypton-helm/blob/feature_add_xenondb_logo/docs/images/logo_xenondb.png
