apiVersion: mysql.radondb.com/v1alpha1
kind: MysqlBackup
metadata:
  name: mysqlbackup-sample2
spec:
  # Add fields here
  # hostname: sample-mysql-0
  clustname: sample
  BackupToNFS: 10.10.131.145


