apiVersion: mysql.radondb.com/v1alpha1
kind: Backup
metadata:
  name: backup-sample
spec:
  # Add fields here
  image: radondb/mysql57-sidecar:v2.2.0
  # hostname if empty, use the leader as hostname
  hostname: sample-mysql-0
  clustername: sample
  # nfsServerAddress: ""
