apiVersion: mysql.radondb.com/v1alpha1
kind: Backup
metadata:
  name: backup-sample
spec:
  # Add fields here
  image: radondb/mysql57-sidecar:v2.4.0-alhpa
  # hostname if empty, use the leader as hostname
  hostName: sample-mysql-0
  clusterName: sample
  # nfsServerAddress: ""