
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.1
  creationTimestamp: null
  name: mysqlbackups.mysql.radondb.com
spec:
  group: mysql.radondb.com
  names:
    kind: MysqlBackup
    listKind: MysqlBackupList
    plural: mysqlbackups
    singular: mysqlbackup
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: MysqlBackup is the Schema for the mysqlbackups API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: MysqlBackupSpec defines the desired state of MysqlBackup
            properties:
              backupToPVC:
                description: Represents the name of backup to PVC
                type: string
              clustname:
                type: string
              hostname:
                description: HostName represents the host for which to take backup
                type: string
            required:
            - clustname
            - hostname
            type: object
          status:
            description: MysqlBackupStatus defines the observed state of MysqlBackup
            properties:
              completed:
                description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                  of cluster Important: Run "make" to regenerate code after modifying
                  this file'
                type: boolean
              conditions:
                description: Conditions represents the backup resource conditions
                  list.
                items:
                  description: BackupCondition defines condition struct for backup
                    resource
                  properties:
                    lastTransitionTime:
                      description: LastTransitionTime
                      format: date-time
                      type: string
                    message:
                      description: Message
                      type: string
                    reason:
                      description: Reason
                      type: string
                    status:
                      description: Status of the condition, one of (\"True\", \"False\",
                        \"Unknown\")
                      type: string
                    type:
                      description: type of cluster condition, values in (\"Ready\")
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
